In [1]:
import numpy as np

In [3]:
liste = [1,2,3,4,5]
numpy_array = np.array(liste)
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
liste_2d = [[1,2,3],[4,5,6],[7,8,9]]
liste_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
numpy_array_2d = np.array(liste_2d)
numpy_array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
numpy_array_2d_1 = np.array([[7,8,9],[1,2,3],[4,5,6]])
numpy_array_2d_1

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
sifir_matrisi = np.zeros((3,4))
sifir_matrisi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
birler_matrisi = np.ones((3,4))
birler_matrisi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
aralik_array = np.arange(1,11)
aralik_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
array = np.array([1,2,3])
array.shape

(3,)

In [11]:
array1 = np.array([[1,2,3],[4,5,6]])
array1.shape

(2, 3)

In [12]:
array2 = np.array([[1,2,3],[4,5,6],[4,5,6]])
array2.shape

(3, 3)

In [13]:
array.ndim

1

In [14]:
array2.ndim

2

In [15]:
array2.size

9

In [16]:
array.size

3

In [17]:
array.dtype

dtype('int32')

In [18]:
array3 = np.array(["Yusuf","Gokhan","Murat","Unzule"])
array3

array(['Yusuf', 'Gokhan', 'Murat', 'Unzule'], dtype='<U6')

In [19]:
array3.dtype

dtype('<U6')

In [20]:
array3.size

4

In [22]:
array = np.array([1,2,3,4,5])
array[0]

1

In [23]:
array[3]

4

In [24]:
array[-1]

5

In [25]:
array[1:4]

array([2, 3, 4])

In [26]:
array[:3]

array([1, 2, 3])

In [27]:
array[3:]

array([4, 5])

In [28]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array2d[0,1]

2

In [36]:
array2d[-2,-2]

5

In [33]:
array2d[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array2d[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [37]:
array2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [38]:
array2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [39]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [40]:
array1 + array2

array([5, 7, 9])

In [41]:
array1 - array2

array([-3, -3, -3])

In [42]:
array1 * array2

array([ 4, 10, 18])

In [43]:
array1 / array2

array([0.25, 0.4 , 0.5 ])

In [44]:
array1 ** 2

array([1, 4, 9], dtype=int32)

In [45]:
matris1 = np.array([[1,2],[4,5]])
matris2 = np.array([[2,3],[5,6]])
np.dot(matris1,matris2)

array([[12, 15],
       [33, 42]])

In [47]:
matris1 = np.array([[1,2,4],[3,5,7],[8,9,7]])
matris2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matris_carpimi = np.dot(matris1,matris2)

In [48]:
np.sum(matris_carpimi)

744

In [49]:
np.mean(matris_carpimi)

82.66666666666667

In [50]:
np.median(matris_carpimi)

87.0

In [51]:
np.std(matris_carpimi)

32.961256718220625

In [52]:
np.max(matris_carpimi)

141

In [53]:
np.min(matris_carpimi)

37

In [54]:
#Broadcasting

In [55]:
array1 = np.array([1,2,3])
array2 = np.array([[4],[5],[6]])
np.dot(array1,array2)

array([32])

In [58]:
random_float = np.random.random()
random_float

0.45681834906914387

In [64]:
random_int = np.random.randint(1,100)
random_int

83

In [65]:
random_list = np.random.randint(1,100,size=10)
random_list

array([89, 33, 15, 41, 92, 51, 29, 94,  8, 34])

In [66]:
normal_dagilim = np.random.normal(0,1,size=10)
normal_dagilim

array([ 1.29899242,  0.69237572, -0.44698582,  0.07925024,  0.19892386,
       -1.86832712,  1.12247517, -1.41115304,  0.62110539, -0.31572777])

In [67]:
np.mean(normal_dagilim)

-0.002907096139081372

In [68]:
np.std(normal_dagilim)

0.98182147810828